In [1]:
import numpy as np
import pandas as pd

# Question 1

In [2]:
np.__version__

'1.19.5'

# Question 2

In [3]:
pd. __version__

'1.3.1'

In [4]:
df = pd.read_csv("/home/ronald/Documentos/data.csv")
df.head(10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

# Question 3

In [6]:
df[df['Make'] == 'BMW'].describe()

Year   Engine HP  Engine Cylinders  Number of Doors  \
count   334.000000  334.000000        334.000000       334.000000   
mean   2014.347305  326.907186          5.958084         3.161677   
std       4.387983  105.681659          1.728939         0.988324   
min    1995.000000  170.000000          0.000000         2.000000   
25%    2015.000000  240.000000          4.000000         2.000000   
50%    2016.000000  300.000000          6.000000         4.000000   
75%    2016.000000  394.000000          7.500000         4.000000   
max    2017.000000  600.000000         12.000000         4.000000   

       highway MPG    city mpg  Popularity           MSRP  
count   334.000000  334.000000       334.0     334.000000  
mean     29.245509   20.739521      3916.0   61546.763473  
std      10.257037   13.136879         0.0   27982.682153  
min      18.000000   10.000000      3916.0    4697.000000  
25%      25.000000   17.000000      3916.0   42300.000000  
50%      28.000000   20.000000      3916.0   51850.000000  
75%      33.000000   22.000000      3916.0   79725.000000  
max     111.000000  137.000000      3916.0  141200.000000

# Question 4

In [7]:
df[(df['Year'] >= 2015)].isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

# Question 5

In [8]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  11914.00   11845.00          11884.00         11908.00     11914.00   
mean    2010.38     249.39              5.63             3.44        26.64   
std        7.58     109.19              1.78             0.88         8.86   
min     1990.00      55.00              0.00             2.00        12.00   
25%     2007.00     170.00              4.00             2.00        22.00   
50%     2015.00     227.00              6.00             4.00        26.00   
75%     2016.00     300.00              6.00             4.00        30.00   
max     2017.00    1001.00             16.00             4.00       354.00   

       city mpg  Popularity        MSRP  
count  11914.00    11914.00    11914.00  
mean      19.73     1554.91    40594.74  
std        8.99     1441.86    60109.10  
min        7.00        2.00     2000.00  
25%       16.00      549.00    21000.00  
50%       18.00     1385.00    29995.00  
75%       22.00     2009.00    42231.25  
max      137.00     5657.00  2065902.00

In [9]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [11]:
#BEFORE
print(round(df['Engine HP'].mean()))

249


In [12]:
df['Engine HP'].fillna(value=249, inplace=True)

In [13]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP               0
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [15]:
df['Engine HP'].mean()

249.3838341447037

In [17]:
#AFTER
print(round(df['Engine HP'].mean()))

249


# Question 6

In [ ]:
df2 = df[(df['Make'] == 'Rolls-Royce')]
df2 = df2[['Engine HP', 'Engine Cylinders','highway MPG']]


In [29]:
X = df2.drop_duplicates().values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [31]:
XTX = np.matmul(X.T, X)

In [32]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [33]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [34]:
print(np.sum(XTX_inv))

0.032212320677486125


# Question 7

In [36]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]
y

[1000, 1100, 900, 1200, 1000, 850, 1300]

In [39]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
X2 = np.matmul(XTX_inv,X.T)
X2

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [40]:
w = np.matmul(X2,y)
w

array([ 0.19989598, 31.02612262, 31.65378877])